config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  post 'quick_start', to: 'welcome#quick_start', as: 'quick_start'

  resources :games do
    resources :events
    resources :stories do
      resources :plays
    end
    resources :users

    get 'game_changes/since/:version', to: 'game_changes#since', as: 'changes_since'
  end

  if Rails.env.development?
    get 'channel/:game_id', to: 'channel_tests#channel'
    get "/pages/*id" => 'high_voltage/pages#show'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false
  def home
    @form = QuickStartCreator.new
  end

  # POST /games/create_fast
  def quick_start
    @form = QuickStartCreator.new game_params, user_params

    if @form.save
      session[:user_id] = @form.user.id
      redirect_to @form.game
    else
      render :home
    end
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end

  def user_params
    params.require(:user).permit(:name, :observer)
  end
end

app/views/welcome/_quick_start_form.html.haml
= form_tag quick_start_path do
  - error_messages_for @form.game

  = fields_for @form.game do |f|
    %div.form-group
      = f.label :name, 'Name of game:'
      = f.text_field :name, class: 'form-control'
  = fields_for @form.user do |f|
    %div.form-group
      = f.label :name, 'Your name:'
      = f.text_field :name, class: 'form-control'

  = submit_tag 'Create Game', class: 'btn btn-primary'

app/views/welcome/home.html.haml
!!!
%html
%head
  = render 'head'
%body
  %div.jumbotron
    %div.container-fluid
      %h1
        Point Poker
        %small
          estimating for agile teams
      %p
        Let's get started:

        %ol
          %li Create a game
          %li Enter some stories
          %li Share the url to your team members

      %div
        = render 'quick_start_form'