config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home'
  post 'quick_start', to: 'welcome#quick_start', as: 'quick_start'

  resources :games do
    resources :events
    resources :stories do
      resources :plays
    end
    resources :users

    get 'game_changes/since/:version', to: 'game_changes#since', as: 'changes_since'
  end

  if Rails.env.development?
    get 'channel/:game_id', to: 'channel_tests#channel'
    get "/pages/*id" => 'high_voltage/pages#show'
  end
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id           :integer          not null, primary key
#  game_id      :integer          not null
#  description  :string(255)      not null
#  complete     :boolean          default(FALSE), not null
#  lock_version :integer          default(0), not null
#  created_at   :datetime
#  updated_at   :datetime
#  completed_at :datetime
#
# Indexes
#
#  index_stories_on_game_id_and_description  (game_id,description) UNIQUE
#

class Story < ActiveRecord::Base
  belongs_to :game, touch: true
  has_many :plays, dependent: :destroy

  validates :game, presence: true
  validates :description, presence: true, uniqueness: { scope: :game_id }

  # Return string representing average mean of all plays
  def mean
    plays.any? or return 'undefined'
    self.class.mean plays.map(&:value)
  end

  def std_dev
    plays.any? or return 'undefined'
    self.class.standard_deviation plays.map(&:value)
  end

  def coefficient_of_variation
    plays.any? or return 'undefined'
    std_dev.to_f / mean.to_f
  end

  def duration
    completed_at - created_at
  end

  # Math stuff. Could be moved somewhere else. Taken from
  # http://stackoverflow.com/questions/7749568/how-can-i-do-standard-deviation-in-ruby

  def self.sum(a)
    a.inject(0){ |accum, i| accum + i }
  end

  def self.mean(a)
    sum(a) / a.length.to_f
  end

  def self.sample_variance(a)
    m = mean(a)
    sum = a.inject(0){ |accum, i| accum + (i - m) ** 2 }
    sum / (a.length - 1).to_f
  end

  def self.standard_deviation(a)
    Math.sqrt(sample_variance(a))
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_game
  respond_to :json, :html

  # POST /games/:game_id/stories
  # POST /games/:game_id/stories.json
  def create
    @story = @game.stories.build story_params
    story_creator = StoryCreator.new @story

    respond_to do |format|
      if story_creator.save
        format.json do
          render status: :created, location: game_story_url(@story.game, @story)
        end
        format.html do
          redirect_to game_path(@game)
        end
      else
        format.json do
          render status: :unprocessable_entity
        end
        format.html do
          redirect_to game_path(@game)
        end
      end
    end
  end

  private

  def set_game
    @game = Game.find_by_token(params[:game_id])
  end

  def story_params
    params.require(:story).permit(:description)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= form_for [game, story], remote: true, html: {class: 'form-inline'} do |f|
  - error_messages_for story

  %div.form-group
    = f.label :description
    = f.text_field :description, class: 'form-control'
  = f.submit class: 'btn btn-default'

app/views/stories/_long_form.html.haml
%div.panel.panel-default
  %div.panel-heading
    %h3.text-center.panel-title
      The game has started

  %div.panel-body
    %p
      Share this url with your team members so they can join. Only people you share with will be able to join the game.

    %div.well
      = link_to game_url(game)

    %p
      While you're waiting for your team members to join, why not start adding some stories?

  %div.panel-footer
    = form_for [game, story], html: {class: 'form-inline'} do |f|
      - error_messages_for story

      %div.form-group
        = f.label :description, 'Story Description'
        = f.text_field :description, class: 'form-control'
      = f.submit class: 'btn btn-primary'

app/views/stories/_stories.html.haml
%div.panel-group#stories{ 'aria-multiselectable' => true, role: 'tablist' }
  =render stories

app/views/stories/_story.html.haml
%div.panel.panel-default.story{id: dom_id(story), class: story.complete? ? 'panel-info' : 'panel-primary' }
  %div.panel-heading{id: dom_id(story, 'heading'), role: 'tab'}
    %h4.panel-title
      %a.panel-toggle{ 'data-toggle' => 'collapse', 'href' => dom_id(story, '#collapse'), 'aria-expanded' => true, 'aria-controls' => dom_id(story, 'collapse') }
        Story
        = story.description
        - if story.complete?
          - if story.coefficient_of_variation >= 1.0
            -#too high! let's add warnings
            %span.label.label-warning
              = "%.1f" % story.mean
              mean
            %span.label.label-danger
              = "%.1f" % story.std_dev
              std dev

          - else
            %span.label.label-success
              = "%.1f" % story.mean
              mean

          %span.label.label-default
            = distance_of_time_in_words story.created_at, story.completed_at
            duration

  %div.panel-collapse.collapse.in{ id: dom_id(story, 'collapse'), 'aria-labelledby' => dom_id(story, 'heading') }
    %div.panel-body
      %div.plays.playingCards
        - if !story.complete? && !current_user.observer? && story.plays.find_by_user_id(current_user.id).blank?
          = render 'plays/potential'

        - story.plays.each do |play|
          = render play

    - if !story.complete? && !current_user.observer? && story.plays.find_by_user_id(current_user.id).blank?
      %div.panel-footer.create_play
        %h5 Choose card:
        = render partial: 'plays/form', locals: {story: story, play: story.plays.build}